name: Android build CI

on: 
  release:
    types: [published]
  push:
    branches: 
      - master
#    tags:
#      - '3.*'
#  pull_request:
#    branches:
#      - master
#  watch:
#    types: [started]
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: release apk sign
      run: |
        echo "给apk增加签名"
        cp $GITHUB_WORKSPACE/.github/workflows/legado.jks $GITHUB_WORKSPACE/app/legado.jks
        sed '$a\RELEASE_STORE_FILE=./legado.jks'          $GITHUB_WORKSPACE/gradle.properties -i 
        sed '$a\RELEASE_KEY_ALIAS=legado'                 $GITHUB_WORKSPACE/gradle.properties -i
        sed '$a\RELEASE_STORE_PASSWORD=gedoor_legado'     $GITHUB_WORKSPACE/gradle.properties -i
        sed '$a\RELEASE_KEY_PASSWORD=gedoor_legado'       $GITHUB_WORKSPACE/gradle.properties -i
    - name: build with gradle
      run: |
        echo "开始进行release构建"
        chmod +x gradlew
        ./gradlew assembleAppRelease
    - name : upload apk
      uses: actions/upload-artifact@master
      if: always()
      with:
        path: ${{ github.workspace }}/app/build/outputs/apk/app/release/legado.apk
